
["Stat 6"]
	#Defines if the stat is on or off
	"Stat 6" = true
	#Defines which name do you want to use for this stat in the menu
	"Stat 6 Name " = "Dexterity"
	#Defines the ID of the attribute, example: minecraft:generic.attack_speed
	"Stat 6 ID" = "minecraft:generic.attack_speed"
	#The value added to the attribute per level
	"Stat 6 Value" = 0.1
	"Stat 6 Max" = 3.0

[Misc]
	"Stat 6 Default" = 3.5

["Extra 1"]
	"Stat 6 Extra 1 ID" = "aaaa:ff"
	"Stat 6 Extra 1 Value" = 4.0
	"Stat 6 Extra 1 LVL Req" = 1.0
	"Stat 6 Extra 1 Max" = 44.0

["Extra 2"]
	"Stat 6 Extra 2 ID" = "aaa:ddd"
	"Stat 6 Extra 2 Value" = 3.0
	"Stat 6 Extra 2 LVL Req" = 4.0
	"Stat 6 Extra 2 Max" = 33.0

["Extra 3"]
	"Stat 6 Extra 3 ID" = "aaaa:dd"
	"Stat 6 Extra 3 Value" = 33.0
	"Stat 6 Extra 3 LVL Req" = 4.0
	"Stat 6 Extra 3 Max" = 4.0

